[auth]
site_url = "http://localhost:3000"

[auth.email.template.invite]
subject = "Te han invitado"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirma tu registro"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Restablece tu contrase√±a"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Tu enlace de acceso"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirma tu nuevo correo"
content_path = "./supabase/templates/email_change.html"
